### ISSUE TITLE
transparnet background does not work

### ISSUE THREAD

**Issue by dragove** [NTBBloodbath/doom-one.nvim#15]
Thanks for the great color scheme. I love it. After updating to the latest version, transparent doesn't work.
The code in the `Customization variables` doesn't run again after calling the setup function. move this block to `load_colorscheme` does work. I'm not familiar with lua, so I don't know if is not elegant to just move this block into `load_colorscheme` function. So I made no PR. : )

**Comment by dragove** [comment]
Have you ran 'PackerCompile' after change your configuration?

**Comment by aniketgm** [comment]
Didn't know this was a lazy-loader code. Shouldn't 'PackerSync' have don't the job already. I have a setting that runs 'PackerSync', every time there is change in my config. Guess I need to do that for compile as well. Thanks.
