### ISSUE TITLE
Setup function makes overriding highlights inconsistent

### ISSUE THREAD

**Issue by akinsho** [NTBBloodbath/doom-one.nvim#17]
Hi @NTBBloodbath 👋🏿 ,

recently I noticed a setup function was added which is nice but adding it seems to make overriding highlights with my custom highlights work inconsistently. Basically my setup is that on the `Colorscheme` autocommand I call a custom highlight function which I have always had regardless of the colorscheme there are just certain highlights that I want a certain way no matter what colorscheme I use.

Anyway I think that since the setup function also loads the colorschemes highlights it can end up changing the highlights after the colorscheme has already loaded so it happens after the autocommand and my highlight overrides are ignored.

I'm not sure why specifically the plugin needs to load the colorscheme again after setup but am wondering if highlighting by this colorscheme can be restricted to that event otherwise it's impossible to consistently override the colorscheme's highlights.

Does this make sense?

**Comment by akinsho** [comment]
@saifulapm I actually meant the `require'doom-one'.setup{...}` function not the packer setup function. The doom one one actually loads the colorscheme after setup is called which is why I'm experiencing the issue I described, in hindsight maybe it should also call `doautocmd Colorscheme` since it is manually applying highlights but not giving the rest of nvim a heads up that that is happening

**Comment by NTBBloodbath** [comment]
Hey akin,

It's been a really long time, hope you're doing well. It seems like I did finally stopped procrastinating with other projects to procrastinate with this one and did a rewrite (still need to add missing plugins integrations) haha.

It does go back to the good ol' classic Neovim global variables to setup colorscheme settings, not too much breaking changes at all as I did try to keep the same option names from setup function, and also improves performance a bit (at least from my tests).

That said, please let me know if you can give rewrite branch a shot so we can close this issue once I merge it.

Cheers

**Comment by akinsho** [comment]
Hi @NTBBloodbath tried it out and seems to work great 👍🏿 thanks

**Comment by NTBBloodbath** [comment]
Cool thanks, merged rewrite branch!
