### ISSUE TITLE
Cannot distinguish selection when using `:s///c` with `hlsearch`

### ISSUE THREAD

**Issue by Janfel** [NTBBloodbath/doom-one.nvim#27]
When using `:substitute` with the `c` flag while `hlsearch` is on, you cannot distinguish the selected match from the other matches. The issue seems to be that this theme sets the same highlights for `Search` and `IncSearch`. See also `:h hl-IncSearch`.

**Comment by NTBBloodbath** [comment]
Hi, do you have any suggestion about what color should be used for selected match?

**Comment by Janfel** [comment]
No, sorry. But I have seen other colorschemes use bold and/or underlined styles to help with this problem.

**Comment by NTBBloodbath** [comment]
Hmm right, I think both `Search` and `IncSearch` does have bold. It should be enough at first to disable bold from `Search` I guess, I'll push the change so you can tell me if it's a good enough solution.

**Comment by Janfel** [comment]
I don’t think that change is enough. The difference is still easy to miss, at least on my setup, and there is no difference at all if the underlying text is already bold. For now, maybe you can just use the yellow from the color palette, like how [`onenord`](https://github.com/rmehri01/onenord.nvim) does it?

**Comment by NTBBloodbath** [comment]
Sure thing, let me change it right now. It should provide a better difference

**Comment by NTBBloodbath** [comment]
Done, please re-open this issue if there's something wrong.

The background color for `IncSearch` is now yellow and the text color is the same as the default background instead of being the default foreground color (this makes compatibility with both light and dark variants great).

**Comment by Janfel** [comment]
That is way more noticeable. Thanks.
