### ISSUE TITLE
Mac use doom-one

### ISSUE THREAD

**Issue by xuyastc** [NTBBloodbath/doom-one.nvim#35]
Am I using it wrong?
<img width="338" alt="image" src="https://user-images.githubusercontent.com/37319368/203309764-f6057df9-0bf3-409b-919b-c6d6e265a001.png">
<img width="332" alt="image" src="https://user-images.githubusercontent.com/37319368/203309973-3f601de3-4541-4407-ac41-10a9488be236.png">
I just downloaded it and used it without doing anything else, but it didn't work

**Comment by mschilli87** [comment]
@NTBBloodbath: I came across this after running into the same issue:
I installed `doom-one.vim` in homebrew's `nvim` using `vim-plug` and `colorscheme doom-one` resulted in no colors at all. Thanks to your suggestion, I checked `termguicolors` and it was off by default. Adding `set termguicolors` before setting the colorscheme in my `init.vim` fixed the problem for me.
