### ISSUE TITLE
is there a way to change the color of the cursor without changing its shape?

### ISSUE THREAD

**Issue by effinsky** [NTBBloodbath/doom-one.nvim#38]
this pertains to the option:
```
vim.g.doom_one_cursor_coloring = false
```
when I use this option, I get the cursor color, change, yes, but also the shape. could I just get the color to change?

my `vim.opt` cursor setup is: `opt.guicursor = "n-c-sm:block,i-ci-ve:block,r-v-cr-o:block" -- block only`

thanks in advance for the feedback and the theme!

**Comment by NTBBloodbath** [comment]
Hey, as `doom-one` use the default `guicursor` value with highlighting groups added I think you could use something like this according to `:h 'guicursor'`

```lua
vim.opt.guicursor = "n-v-c:block-Cursor,i-ci-ve:block-Cursor,r-cr-o:block-Cursor" -- block only
```

**Comment by effinsky** [comment]
generally my cursor shape is set to working as block only. it's the theme that's changing it when the opt to change cursor color, as you describe it, is switched on. i'm saying it should change only the color, and not the shape.

**Comment by NTBBloodbath** [comment]
> generally my cursor shape is set to working as block only. it's the theme that's changing it when the opt to change cursor color, as you describe it, is switched on. i'm saying it should change only the color, and not the shape.

Please read the answer I gave you carefully. Just don't activate the option from the theme and use the code I sent you, as the theme option is exactly the same as the default values but adding the highlighting group to the cursor.

**Comment by effinsky** [comment]
do what you want. the option named as it is should not behave as it does. either rename the option or change its behavior os that both match. my 2 cents.

**Comment by NTBBloodbath** [comment]
> do what you want. the option named as it is should not behave as it does. either rename the option or change its behavior os that both match. my 2 cents.

No, the option works and is named just as it should, **respecting Neovim's DEFAULTS for the 'guicursor' option and which at least 99% of users use**. Your issue is a very particular use case since you modify the values of that option, so I gave you a snippet so that you get the same result based on your modifications under your Neovim setup.

**Comment by effinsky** [comment]
then it should be annotated as "works only with default neovim guicursor setup". not a hack one has to come here to get a special snippet cause one legitimately tweaked one's cursor settings. you are building on top of those settings and it would be good to account for their flexibility. otherwise it's just brittle design.
