### ISSUE TITLE
Async loading

### ISSUE THREAD

**Issue by akinsho** [NTBBloodbath/doom-one.nvim#9]
Sorry, on a roll this morning.

So I've also noticed a few colorscheme authors making their themes async to try and save milliseconds off the startup time, which is a whole other conversation since I think people have become a bit obsessed with that. Anyway I think a colorscheme isn't a good candidate for being async because a lot of things in a vim setup are dependent on being able to reliably check the colours in the colorscheme after the colorscheme autocommand has run whereas now colours are set at unpredictable times in my case I have highlights which I override for lots of different use cases after calling `colorscheme doom-one` which suddenly can't find the colorscheme colours since there's a race condition, and they aren't set now.

But more generally a lot of plugins use the Colorscheme autocommand to reapply highlighting and so if things are async there will be race conditions there as well. For example, bufferline re applies its highlights when the colorscheme autocommand is called by checking what colours the theme has defined, but now this is likely to fail since those colours will be being set asynchronously.

**Comment by NTBBloodbath** [comment]
Hey akinsho, sorry for the late reply.

To be honest I hadn't seen it from that point and it can be a big problem. If that's the case, I should reverse that change. Not everything should be asynchronous :thinking:

**Comment by akinsho** [comment]
Maybe it can be an option, although tbh (being a little dogmatic) I think a colorscheme is a hard dependency during startup and should be loaded synchronously. I think the current slowness (which I think isn't too bad I get 8ms which is very small already tbh) is due to vim's highlighting being slow but the nvim team are working on a highlighting api, so eventually this will be able to be done via lua and the api so should be much faster at that point.

**Comment by akinsho** [comment]
Actually a thread came up about this on reddit recently thought I'd link here if you hadn't seen it some comments from tj as well [this thread](https://www.reddit.com/r/neovim/comments/ops738/new_async_doesnt_do_what_you_think_it_does/) and also the comments in [this thread](https://www.reddit.com/r/neovim/comments/opipij/guide_tips_and_tricks_to_reduce_startup_and/h666vog?utm_source=share&utm_medium=web2x&context=3)

**Comment by NTBBloodbath** [comment]
Thank you so much for sharing it!

Also sorry for the delay, I wasn't home so I couldn't make the changes again. I'll try to revert the async stuff today!

**Comment by NTBBloodbath** [comment]
Alright so I reverted that async stuff, thank you very much for mentioning the problems that brings in a colorscheme!
